- name: Clone project
  git: repo={{git_repository}} dest={{project_dir}} accept_hostkey=yes
  notify: Install requirements.txt
  tags: app, backend

- name: Create environmental variable
  template: src=env.j2
            dest={{ base_dir }}/.env
  tags: app, backend

- name: Install envvars
  pip: name=envvars virtualenv={{virtualenv_dir}}/smartpad virtualenv_python=/usr/bin/python3.4
  tags: app, backend
