---
- hosts: development
  become_user: root
  remote_user: root
  connection: ssh
  gather_facts: no
  vars_files:
    - env_vars/development.yml

  roles:
    - common/directories
    - common/base
    - common/postgres
    - common/nginx

    - development/db
