- name: Install database requirements
  yum: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - postgresql-server
    - postgresql-contrib
    - postgresql-devel
  tags: packages, postgres

- name: Create database cluster
  command: /usr/bin/postgresql-setup initdb
  tags: packages, postgres

- name: Enable postgres
  command: /usr/bin/systemctl enable postgresql
  tags: packages, postgres

- name: Restart postgresql
  service: name=postgresql enabled=yes state=restarted
  tags: packages, postgres
