- name: Ensure project directories exists
  file: dest={{ item }}  state=directory mode=0775
  with_items:
    - "{{ base_dir }}"
    - "{{ virtualenv_dir }}"
    - "{{ project_dir }}"
  tags: app
